FROM gobase

MAINTAINER dxwsker@qq.com

COPY . /go/src/github.com/vmware/harbor

WORKDIR /go/src/github.com/vmware/harbor/jobservice

RUN go build -v -a -o /go/bin/harbor_jobservice \
    && chmod u+x /go/bin/harbor_jobservice 
WORKDIR /go/bin/
ENTRYPOINT ["/go/bin/harbor_jobservice"]
